export interface RTGameRoomInterface {
    id: number,
    type: 'findgame' | 'invite',
    status: 'lobby' | 'playing' | 'paused' | 'finished';
    player1IsConnected: boolean,
    player2IsConnected: boolean,
    player1Name: string,
    player2Name: string,
    player1SmallRacketVote : boolean,
    player2SmallRacketVote : boolean,
    player1LongerGameVote : boolean,
    player2LongerGameVote : boolean,
    timeToStart: number,
    creationDate: number,
    elepsedTime: number,
    racketVelocity: number,
    player1Score: number,
    player2Score: number,
    racketWidth: number,
    racketHeight: number,
    player1RacketXPosition: number,
    player2RacketXPosition: number,
    player1RacketPosition: number,
    player2RacketPosition: number,
    gameFinishScore: number,
    width: number,
    height: number,
    ballRadiues: number,
    ballX: number,
    ballY: number,
    ballVx: number,
    ballVy: number,
    firstBallPosition: number,
    player1PauseTime: number,
    player2PauseTime: number,
    timeToPausePlayer1: number,
    timeToPausePlayer2: number,
    pausedtime: number,
    lobbyTime: number,
}

export const defaultGameRoom : RTGameRoomInterface = {
    id: 0,
    type: 'findgame',
    status: 'lobby',
    player1IsConnected: false,
    player2IsConnected: false,
    player1Name: "",
    player2Name: "",
    player1SmallRacketVote : false,
    player2SmallRacketVote : false,
    player1LongerGameVote : false,
    player2LongerGameVote : false,
    gameFinishScore: 10,
    creationDate: 0,
    timeToStart: 3000,
    elepsedTime: 0,
    racketVelocity: 10,
    player1Score: 0,
    player2Score: 0,
    racketWidth: 10,
    racketHeight: 60,
    player1RacketXPosition: 0,
    player2RacketXPosition: 360 - 10, //10 is the racketwidth.
    player1RacketPosition: 100,
    player2RacketPosition: 100,
    width: 360,
    height: 270,
    ballRadiues: 10,
    ballX: 100,
    ballY: 100,
    ballVx: 7,
    ballVy: 7,
    firstBallPosition: 100,
    pausedtime: 0,
    player1PauseTime: 10000,
    player2PauseTime: 10000,
    timeToPausePlayer1: 3000, //random number
    timeToPausePlayer2: 3000,
    lobbyTime: 10000,
};
